[package]
name = "vortex"

edition = "2021"
version = "0.1.0"

authors = ['pyc4che']

[dependencies]
tokio = { version = "1", features = ["full"] }
bpaf = {version = "0.9.6", features = ["derive", "bright-color"]}
